import { describe, expect, it } from "bun:test"
import { decodePaint, encodePaint, type PaintNode, paintStates } from "../paint-rle.js"

// Cross-validation vectors generated by the spike-verified Python implementation used to build
// the original decoder this package ports (prototyper/paint_rle.py, byte-identical vs Bambu
// Studio 02.07 on 13,656 real painted triangles). hex = python encode(tree); states =
// python states(tree). This port must read exactly what that verified encoder wrote.
const VECTORS: Array<{ name: string; hex: string; states: number[] }> = [
  { name: "unpainted leaf", hex: "0", states: [0] },
  { name: "slot-1 leaf", hex: "4", states: [1] },
  { name: "slot-2 leaf", hex: "8", states: [2] },
  { name: "escaped state 3", hex: "0C", states: [3] },
  { name: "escaped state 7", hex: "4C", states: [7] },
  { name: "escaped state 16 (AMS-HT range)", hex: "DC", states: [16] },
  { name: "2-way split", hex: "841", states: [1, 2] },
  { name: "3-way split with special side", hex: "4C40A", states: [0, 1, 7] },
  { name: "nested splits, escape + plain mix", hex: "03C3CE4801C17", states: [0, 1, 2, 4, 6] },
  { name: "deep escape mix", hex: "0FC0C51", states: [0, 3, 18] },
]

describe("paintStates — decodes the verified Python encoder's output", () => {
  for (const v of VECTORS) {
    it(v.name, () => {
      expect([...paintStates(v.hex)].sort((a, b) => a - b)).toEqual(v.states)
    })
  }
})

describe("decodePaint/encodePaint — round-trip", () => {
  for (const v of VECTORS) {
    it(v.name, () => {
      expect(encodePaint(decodePaint(v.hex))).toBe(v.hex)
    })
  }

  it("rebuilds the exact tree for a nested split", () => {
    const tree = decodePaint("841")
    const expected: PaintNode = {
      kind: "split",
      splitSides: 1,
      specialSide: 0,
      children: [
        { kind: "leaf", state: 1 },
        { kind: "leaf", state: 2 },
      ],
    }
    expect(tree).toEqual(expected)
  })
})

describe("malformed input throws (callers degrade to the full filament list)", () => {
  it("rejects non-hex characters", () => {
    expect(() => paintStates("XYZ")).toThrow()
  })

  it("rejects truncated streams", () => {
    // "5" = split_sides 1 + special 1, then demands 2 children the stream doesn't contain.
    expect(() => paintStates("5")).toThrow()
  })

  it("rejects set trailing bits (mis-parse signal)", () => {
    // "F0" leaves set bits beyond the parsed leaf.
    expect(() => paintStates("F0")).toThrow()
  })

  it("rejects the empty string", () => {
    expect(() => paintStates("")).toThrow()
  })
})
